apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: nolabelregistry/nolabel-backend:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://python-app-service.nolabel-dev.svc.cluster.local"
